name: Parkour
version: 1.0.0
main: Parkour\utils\Main
api: 5.0.0
description: Plugin untuk mengelola aktivitas parkour dalam permainan Minecraft.
author: VsrStudio
permissions:
  parkour.command:
    description: Memberikan akses untuk menggunakan perintah parkour
    default: true
